#!/bin/bash
# 检查 Server 端和 Flask 端日志中的 Level 值

echo "=========================================="
echo "检查 Server 端日志（Celery worker）"
echo "=========================================="
echo ""
echo "请查看 Celery worker 的日志，查找以下内容："
echo "  [调试] Pipeline 返回的 Level 值"
echo "  [调试] JSON 序列化测试"
echo "  [调试] JSON 反序列化后的 Level 值"
echo ""
echo "如果看到 Level=2, 0, 0，说明 Pipeline 输出正确"
echo "如果看到 Level=1, 1, 1，说明问题在 Pipeline 端"
echo ""
echo "=========================================="
echo "检查 Flask 端日志"
echo "=========================================="
echo ""
echo "请查看 Flask 服务器的日志，查找以下内容："
echo "  [调试] Flask 接收到的 CephalometricMeasurements Level 值"
echo "  [调试] 原始 JSON 数据"
echo ""
echo "如果看到 Level=2, 0, 0，说明 Flask 接收正确"
echo "如果看到 Level=1, 1, 1，说明问题在数据传输过程中"
echo ""
echo "=========================================="
echo "如何查看日志："
echo "=========================================="
echo ""
echo "1. Server 端（Celery worker）日志："
echo "   查看运行 Celery worker 的终端输出"
echo "   或查看日志文件（如果配置了日志文件）"
echo ""
echo "2. Flask 端日志："
echo "   查看运行 Flask 服务器的终端输出"
echo "   应该能看到 '收到回调' 和 '[调试]' 信息"
echo ""

